
  CREATE TABLE "WOOGIE"."MEMBER" 
   (	"EMAIL" VARCHAR2(320 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE), 
	"PW" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(100 BYTE), 
	"INTRO" CLOB, 
	"REG_DT" DATE DEFAULT sysdate, 
	"MEMBER_NO" NUMBER, 
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("INTRO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;


  CREATE TABLE "WOOGIE"."POST" 
   (	"POST_NO" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(200 BYTE), 
	"TEXT_MD" CLOB, 
	"TEXT_HTML" CLOB, 
	"READ_CNT" NUMBER DEFAULT 0, 
	"LIKE_CNT" NUMBER, 
	"HATE_CNT" NUMBER, 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"REG_DT" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"MOD_DT" DATE, 
	"MEMBER_EMAIL" VARCHAR2(320 BYTE), 
	 CONSTRAINT "POST_PK" PRIMARY KEY ("POST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "POST_FK1" FOREIGN KEY ("MEMBER_EMAIL")
	  REFERENCES "WOOGIE"."MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("TEXT_MD") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TEXT_HTML") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;


  CREATE TABLE "WOOGIE"."REPLY" 
   (	"REPLY_NO" NUMBER NOT NULL ENABLE, 
	"CONTENTS" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"DEPTH" NUMBER(1,0), 
	"PARENT_REPLY" NUMBER, 
	"DELETE_CHECK" NUMBER(1,0), 
	"REG_DT" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"POST_NO" NUMBER NOT NULL ENABLE, 
	"MEMBER_EMAIL" VARCHAR2(320 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "REPLY_PK" PRIMARY KEY ("REPLY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "REPLY_FK1" FOREIGN KEY ("POST_NO")
	  REFERENCES "WOOGIE"."POST" ("POST_NO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "WOOGIE"."STORAGE" 
   (	"STORAGE_NO" NUMBER NOT NULL ENABLE, 
	"STORE_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"REG_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MEMBER_EMAIL" VARCHAR2(320 BYTE) NOT NULL ENABLE, 
	"POST_NO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_STORAGE" PRIMARY KEY ("STORAGE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "STORAGE_FK1" FOREIGN KEY ("POST_NO")
	  REFERENCES "WOOGIE"."POST" ("POST_NO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOOGIE"."STORAGE"."STORAGE_NO" IS '보관번호';
   COMMENT ON COLUMN "WOOGIE"."STORAGE"."STORE_TYPE" IS '유형';
   COMMENT ON COLUMN "WOOGIE"."STORAGE"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "WOOGIE"."STORAGE"."MEMBER_EMAIL" IS '멤버이메일';
   COMMENT ON COLUMN "WOOGIE"."STORAGE"."POST_NO" IS '게시물번호';
   COMMENT ON TABLE "WOOGIE"."STORAGE"  IS '보관함';


  CREATE TABLE "WOOGIE"."FOLLOW" 
   (	"FOLLOW_NO" NUMBER NOT NULL ENABLE, 
	"FOLLOWING_EMAIL" VARCHAR2(320 BYTE) NOT NULL ENABLE, 
	"FOLLOWED_EMAIL" VARCHAR2(320 BYTE) NOT NULL ENABLE, 
	"REG_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_FOLLOW" PRIMARY KEY ("FOLLOW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FOLLOW_FK1" FOREIGN KEY ("FOLLOWING_EMAIL")
	  REFERENCES "WOOGIE"."MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FOLLOW_FK2" FOREIGN KEY ("FOLLOWED_EMAIL")
	  REFERENCES "WOOGIE"."MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOOGIE"."FOLLOW"."FOLLOW_NO" IS '팔로우번호';
   COMMENT ON COLUMN "WOOGIE"."FOLLOW"."FOLLOWING_EMAIL" IS '팔로잉이메일';
   COMMENT ON COLUMN "WOOGIE"."FOLLOW"."FOLLOWED_EMAIL" IS '팔로워이메일
';
   COMMENT ON COLUMN "WOOGIE"."FOLLOW"."REG_DT" IS '팔로우등록일';
   COMMENT ON TABLE "WOOGIE"."FOLLOW"  IS '팔로워';


  CREATE TABLE "WOOGIE"."IMAGE" 
   (	"IMAGE_NO" NUMBER NOT NULL ENABLE, 
	"MAIN_IMAGE" NUMBER NOT NULL ENABLE, 
	"ORG_NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"SAVE_NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"PATH" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	"FILE_SIZE" NUMBER NOT NULL ENABLE, 
	"FILE_EXT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FROM_TB" NUMBER NOT NULL ENABLE, 
	"FROM_NO" NUMBER NOT NULL ENABLE, 
	"REG_DT" DATE DEFAULT SYSDATE /* 저장일 */, 
	"FULL_PATH" VARCHAR2(256 BYTE), 
	 CONSTRAINT "PK_IMAGE" PRIMARY KEY ("IMAGE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOOGIE"."IMAGE"."IMAGE_NO" IS '이미지번호';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."MAIN_IMAGE" IS '메인이미지';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."ORG_NAME" IS '원본파일명';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."SAVE_NAME" IS '저장파일명';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."PATH" IS '경로';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."FILE_SIZE" IS '파일용량';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."FILE_EXT" IS '확장자';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."FROM_TB" IS '출처';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."FROM_NO" IS '출처번호';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."REG_DT" IS '저장일';
   COMMENT ON COLUMN "WOOGIE"."IMAGE"."FULL_PATH" IS '풀패스';
   COMMENT ON TABLE "WOOGIE"."IMAGE"  IS '이미지';

